//go:build mage

package main

import (
	"fmt"
	"os"
	"runtime"
	"strings"

	"github.com/magefile/mage/sh"
)

const tailwindVersion = "v4.3.0"

// tailwindVersionMarker records which CLI version is installed so InstallTailwind
// re-downloads when the pinned version changes (e.g. the v3 -> v4 bump).
const tailwindVersionMarker = "./tailwind/.tailwind-version"

// InstallTailwind downloads the Tailwind standalone CLI for the current platform.
// Re-downloads when the installed version doesn't match tailwindVersion.
func InstallTailwind() error {
	binary := tailwindBinaryPath()
	if _, err := os.Stat(binary); err == nil {
		if v, _ := os.ReadFile(tailwindVersionMarker); string(v) == tailwindVersion {
			fmt.Printf("Tailwind %s already installed, skipping.\n", tailwindVersion)
			return nil
		}
		fmt.Println("Tailwind version changed, re-downloading.")
		_ = os.Remove(binary)
	}

	url := tailwindDownloadURL()
	fmt.Printf("Downloading Tailwind %s from %s\n", tailwindVersion, url)

	if err := sh.Run("curl", "-sLo", binary, url); err != nil {
		return err
	}
	if err := sh.Run("chmod", "+x", binary); err != nil {
		return err
	}
	return os.WriteFile(tailwindVersionMarker, []byte(tailwindVersion), 0644)
}

// BuildCSS compiles Tailwind CSS. Tailwind v4 is CSS-first (no -c config flag);
// sources/theme live in tailwind/input.css. writeFlintSource points Tailwind at
// the flint-ui component templates so their utility classes get compiled.
func BuildCSS() error {
	if err := writeFlintSource(); err != nil {
		return err
	}
	return sh.Run(
		tailwindBinaryPath(),
		"-i", "./tailwind/input.css",
		"-o", "./web/static/css/site.css",
		"--minify",
	)
}

// writeFlintSource resolves the flint-ui module directory and writes a
// (gitignored) CSS file with a @source directive so Tailwind scans flint-ui's
// templates for class names. Generated rather than vendored so the path tracks
// the resolved module version automatically.
func writeFlintSource() error {
	dir, err := sh.Output("go", "list", "-m", "-f", "{{.Dir}}", "github.com/flintcraftstudio/flint-ui")
	if err != nil {
		return fmt.Errorf("resolve flint-ui module dir: %w", err)
	}
	dir = strings.TrimSpace(dir)
	// flint-ui keeps its Tailwind class strings in classes.go (and *_templ.go),
	// not the .templ files, so scan the Go sources too.
	content := fmt.Sprintf(
		"/* generated by mage BuildCSS — do not edit */\n@source %q;\n@source %q;\n",
		dir+"/components/**/*.go",
		dir+"/components/**/*.templ",
	)
	return os.WriteFile("./tailwind/flint-source.css", []byte(content), 0644)
}

// GenerateTempl runs templ generate
func GenerateTempl() error {
	return sh.Run("templ", "generate")
}

// GenerateSqlc runs sqlc generate
func GenerateSqlc() error {
	return sh.Run("sqlc", "generate")
}

// Generate runs templ generate and sqlc generate
func Generate() error {
	if err := GenerateTempl(); err != nil {
		return err
	}
	return GenerateSqlc()
}

// MigrateUp runs all pending goose migrations
func MigrateUp() error {
	return sh.Run("goose", "-dir", "migrations", "sqlite3", dbPath(), "up")
}

// MigrateDown rolls back the last goose migration
func MigrateDown() error {
	return sh.Run("goose", "-dir", "migrations", "sqlite3", dbPath(), "down")
}

// MigrateStatus shows the current migration state
func MigrateStatus() error {
	return sh.Run("goose", "-dir", "migrations", "sqlite3", dbPath(), "status")
}

// CreateMigration scaffolds a new goose migration file
func CreateMigration(name string) error {
	return sh.Run("goose", "-dir", "migrations", "create", name, "sql")
}

// Seed creates an admin user. Usage: mage seed admin@example.com password123
func Seed(email, password string) error {
	return sh.Run("go", "run", "./cmd/seed", email, password)
}

// SeedData wipes and repopulates bookings/questions/waitlist with sample data
// for exercising the admin dashboard. Leaves users/sessions/settings untouched.
func SeedData() error {
	return sh.Run("go", "run", "./cmd/seeddata")
}

func dbPath() string {
	if p := os.Getenv("DB_PATH"); p != "" {
		return p
	}
	return "./data/app.db"
}

// BuildGo compiles the Go binary
func BuildGo() error {
	if err := Generate(); err != nil {
		return err
	}
	return sh.Run("go", "build", "-o", "./bin/server", "./cmd/server")
}

// Build runs a full production build
func Build() error {
	if err := BuildCSS(); err != nil {
		return err
	}
	return BuildGo()
}

// Dev regenerates code, rebuilds assets, and starts the server
func Dev() error {
	if err := Build(); err != nil {
		return err
	}
	return Run()
}

// Run starts the server
func Run() error {
	return sh.Run("./bin/server")
}

func tailwindBinaryPath() string {
	if runtime.GOOS == "windows" {
		return "./tailwind/tailwindcss.exe"
	}
	return "./tailwind/tailwindcss"
}

func tailwindDownloadURL() string {
	os := runtime.GOOS
	arch := runtime.GOARCH

	osName := map[string]string{
		"darwin":  "macos",
		"linux":   "linux",
		"windows": "windows",
	}[os]

	archName := map[string]string{
		"amd64": "x64",
		"arm64": "arm64",
	}[arch]

	ext := ""
	if os == "windows" {
		ext = ".exe"
	}

	return fmt.Sprintf(
		"https://github.com/tailwindlabs/tailwindcss/releases/download/%s/tailwindcss-%s-%s%s",
		tailwindVersion, osName, archName, ext,
	)
}